import type { Locale } from './i18n'

export interface PlayMessages {
  game: string; history: string; newGame: string; vsComputer: string; twoPlayers: string
  offlineAiUnavailable: string; difficulty: string; playAs: string; white: string; black: string
  start: string; matching: string; onlineMatch: string; initialTime: string; increment: string
  minutes: string; seconds: string; createRoom: string; join: string; roomCodePlaceholder: string
  matchmakingHint: string; turn: string; toMove: string; engineThinking: string
  undo: string; saveGame: string; moves: string; noMoves: string
}

export const playMessages: Record<Locale, PlayMessages> = {
  'zh-CN': { game:'对局',history:'历史',newGame:'新对局',vsComputer:'人机对战',twoPlayers:'双人对战',offlineAiUnavailable:'离线状态下无法人机对战，可切换双人对战或去推演。',difficulty:'难度',playAs:'执子',white:'白方',black:'黑方',start:'开始',matching:'匹配中...',onlineMatch:'在线匹配',initialTime:'基础时间',increment:'每步加秒',minutes:'分钟',seconds:'秒',createRoom:'创建好友房',join:'加入',roomCodePlaceholder:'输入房间码',matchmakingHint:'在线匹配优先等待真人；约 8 秒未匹配到时自动进入人机局。',turn:'轮到',toMove:'走',engineThinking:'引擎思考中…',undo:'悔棋',saveGame:'保存棋谱',moves:'着法',noMoves:'尚无着法' },
  en: { game:'Game',history:'History',newGame:'New game',vsComputer:'Vs computer',twoPlayers:'Two players',offlineAiUnavailable:'Computer play is unavailable offline. Choose two players or analysis.',difficulty:'Difficulty',playAs:'Play as',white:'White',black:'Black',start:'Start',matching:'Matching...',onlineMatch:'Online match',initialTime:'Initial time',increment:'Increment',minutes:'minutes',seconds:'seconds',createRoom:'Create friend room',join:'Join',roomCodePlaceholder:'Enter room code',matchmakingHint:'We look for a human opponent first, then start a computer game after about 8 seconds.',turn:'Turn:',toMove:'to move',engineThinking:'Engine thinking…',undo:'Undo',saveGame:'Save game',moves:'Moves',noMoves:'No moves yet' },
  es: { game:'Partida',history:'Historial',newGame:'Nueva partida',vsComputer:'Contra el ordenador',twoPlayers:'Dos jugadores',offlineAiUnavailable:'No se puede jugar contra el ordenador sin conexión. Elige dos jugadores o análisis.',difficulty:'Dificultad',playAs:'Jugar con',white:'Blancas',black:'Negras',start:'Comenzar',matching:'Buscando...',onlineMatch:'Partida en línea',initialTime:'Tiempo inicial',increment:'Incremento',minutes:'minutos',seconds:'segundos',createRoom:'Crear sala',join:'Unirse',roomCodePlaceholder:'Código de sala',matchmakingHint:'Primero buscamos un rival humano; después de unos 8 segundos comienza una partida contra el ordenador.',turn:'Turno:',toMove:'juegan',engineThinking:'El motor está pensando…',undo:'Deshacer',saveGame:'Guardar partida',moves:'Movimientos',noMoves:'Aún no hay movimientos' },
  fr: { game:'Partie',history:'Historique',newGame:'Nouvelle partie',vsComputer:'Contre l’ordinateur',twoPlayers:'Deux joueurs',offlineAiUnavailable:'Le jeu contre l’ordinateur est indisponible hors ligne. Choisissez deux joueurs ou l’analyse.',difficulty:'Difficulté',playAs:'Jouer avec',white:'Blancs',black:'Noirs',start:'Commencer',matching:'Recherche...',onlineMatch:'Partie en ligne',initialTime:'Temps initial',increment:'Incrément',minutes:'minutes',seconds:'secondes',createRoom:'Créer une salle',join:'Rejoindre',roomCodePlaceholder:'Code de la salle',matchmakingHint:'Nous cherchons d’abord un adversaire humain, puis lançons une partie contre l’ordinateur après environ 8 secondes.',turn:'Tour :',toMove:'jouent',engineThinking:'Le moteur réfléchit…',undo:'Annuler',saveGame:'Enregistrer',moves:'Coups',noMoves:'Aucun coup' },
  de: { game:'Partie',history:'Verlauf',newGame:'Neue Partie',vsComputer:'Gegen Computer',twoPlayers:'Zwei Spieler',offlineAiUnavailable:'Computerspiel ist offline nicht verfügbar. Wähle zwei Spieler oder Analyse.',difficulty:'Stärke',playAs:'Spielen als',white:'Weiß',black:'Schwarz',start:'Starten',matching:'Suche...',onlineMatch:'Online-Partie',initialTime:'Grundzeit',increment:'Inkrement',minutes:'Minuten',seconds:'Sekunden',createRoom:'Freundesraum erstellen',join:'Beitreten',roomCodePlaceholder:'Raumcode eingeben',matchmakingHint:'Zuerst suchen wir einen Menschen; nach etwa 8 Sekunden startet eine Computerpartie.',turn:'Am Zug:',toMove:'',engineThinking:'Engine rechnet…',undo:'Zurücknehmen',saveGame:'Partie speichern',moves:'Züge',noMoves:'Noch keine Züge' },
  id: { game:'Partai',history:'Riwayat',newGame:'Partai baru',vsComputer:'Lawan komputer',twoPlayers:'Dua pemain',offlineAiUnavailable:'Lawan komputer tidak tersedia saat offline. Pilih dua pemain atau analisis.',difficulty:'Kesulitan',playAs:'Bermain sebagai',white:'Putih',black:'Hitam',start:'Mulai',matching:'Mencari...',onlineMatch:'Partai online',initialTime:'Waktu awal',increment:'Tambahan waktu',minutes:'menit',seconds:'detik',createRoom:'Buat ruang teman',join:'Gabung',roomCodePlaceholder:'Masukkan kode ruang',matchmakingHint:'Kami mencari lawan manusia terlebih dahulu, lalu memulai partai komputer setelah sekitar 8 detik.',turn:'Giliran:',toMove:'melangkah',engineThinking:'Mesin sedang berpikir…',undo:'Batalkan langkah',saveGame:'Simpan partai',moves:'Langkah',noMoves:'Belum ada langkah' },
  ja: { game:'対局',history:'履歴',newGame:'新規対局',vsComputer:'コンピューター対戦',twoPlayers:'2人対戦',offlineAiUnavailable:'オフラインではコンピューター対戦を利用できません。2人対戦または検討を選んでください。',difficulty:'強さ',playAs:'持ち駒',white:'白',black:'黒',start:'開始',matching:'マッチング中…',onlineMatch:'オンライン対局',initialTime:'持ち時間',increment:'加算時間',minutes:'分',seconds:'秒',createRoom:'友達用ルームを作成',join:'参加',roomCodePlaceholder:'ルームコードを入力',matchmakingHint:'まず対人マッチを探し、約8秒で見つからない場合はコンピューター対戦を開始します。',turn:'手番：',toMove:'',engineThinking:'エンジン思考中…',undo:'待った',saveGame:'棋譜を保存',moves:'指し手',noMoves:'まだ指し手がありません' },
  ko: { game:'대국',history:'기록',newGame:'새 대국',vsComputer:'컴퓨터 대전',twoPlayers:'2인 대전',offlineAiUnavailable:'오프라인에서는 컴퓨터 대전을 이용할 수 없습니다. 2인 대전이나 분석을 선택하세요.',difficulty:'난이도',playAs:'진영',white:'백',black:'흑',start:'시작',matching:'매칭 중…',onlineMatch:'온라인 대국',initialTime:'기본 시간',increment:'초읽기 추가',minutes:'분',seconds:'초',createRoom:'친구 방 만들기',join:'참가',roomCodePlaceholder:'방 코드 입력',matchmakingHint:'먼저 사람 상대를 찾고, 약 8초 후에는 컴퓨터 대국을 시작합니다.',turn:'차례:',toMove:'',engineThinking:'엔진 계산 중…',undo:'무르기',saveGame:'기보 저장',moves:'수순',noMoves:'아직 수가 없습니다' },
}
